name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: zwping/fork-sync@v1.6.5
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: jaywcjlove # fork 的上游仓库 user
          head: gh-pages # fork 的上游仓库 branch
          base: gh-pages # 本地仓库 branch