name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch upstream
        run: git remote add upstream https://github.com/jaywcjlove/reference.git

      - name: Merge upstream
        run: |
          git fetch upstream
          git checkout gh-pages
          git merge upstream/gh-pages
          git push